" location ~/.vimrc
" # mkdir -p ~/.vim/pack/themes/start
" # cd ~/.vim/pack/themes/start
" # git clone https://github.com/dracula/vim.git dracula
packadd! dracula
syntax on
colorscheme dracula
set number
set smartindent
set tabstop=4
set colorcolumn=80
source $VIMRUNTIME/mswin.vim
behave mswin
nnoremap <A-down> <C-W><C-J>
nnoremap <A-up> <C-W><C-K>
nnoremap <A-right> <C-W><C-L>
nnoremap <A-left> <C-W><C-H>
inoremap <C-k> <C-o>dd
map <C-up> :tabr<cr>
map <C-down> :tabl<cr>
map <C-left> :tabp<cr>
map <C-right> :tabn<cr>
map <C-o> :tabnew \| Explore<cr> 
map <C-w> :q<cr>

" problems with Ctrl+C Ctrl+V on some terminals
vmap <C-c> y<Esc>i
vmap <C-x> d<Esc>i
map <C-v> pi
imap <C-v> <Esc>pi
imap <C-z> <Esc>ui

" arrows can be used for selection
vmap <Up> k
vmap <Down> j
vmap <Left> h
vmap <Right> l

let g:netrw_banner = 0
let g:netrw_browse_split = 0
au VimEnter * silent execute '!echo -ne "\e[6 q"' | set cul | redraw!
au VimLeave * silent execute '!echo -ne "\e[ q"' | redraw!
au BufNewFile,BufRead Jenkinsfile setf groovy


inoremap " ""<left>
inoremap ' ''<left>
inoremap ( ()<left>
inoremap [ []<left>
inoremap { {}<left>
inoremap {<CR> {<CR>}<ESC>O
inoremap {;<CR> {<CR>};<ESC>O

