" location ~/.vimrc
syntax on
set number
source $VIMRUNTIME/mswin.vim
behave mswin
nnoremap <A-down> <C-W><C-J>
nnoremap <A-up> <C-W><C-K>
nnoremap <A-right> <C-W><C-L>
nnoremap <A-left> <C-W><C-H>
map <C-up> :tabr<cr>
map <C-down> :tabl<cr>
map <C-left> :tabp<cr>
map <C-right> :tabn<cr>
map <C-o> :tabnew \| Explore<cr> 
map <C-w> :q<cr>
let g:netrw_banner = 0
let g:netrw_browse_split = 0
